### ISSUE TITLE
Integrate the new KDBX 4.1 format

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#956]
Dominik will soon release KeePass 2.48 with the new KDBX 4.1 format:
https://keepass.info/help/kb/kdbx_4.1.html

 - [x] group with a tag. (#633)
 - [x] entry for which the password quality estimation is disabled. (#869)
 - [x] custom icon with a non-empty name (#976)
 - [x] custom icon with last modification time (#977)
 - [x] custom data item with a last modification time (#977)
 - [x] manage previous parent group (#978)

The goal is not to make the features but that the format and the corresponding parameters are recognized so that they are not lost during a transfer. The features will be developed later

**Comment by dequally** [comment]
> Dominik will soon release KeePass 2.48 with the new KDBX 4.1 format:
> https://keepass.info/help/kb/kdbx_4.1.html

Will the database then automatically opgrade to KDBX 4.1?

**Comment by dequally** [comment]
My database is kdbx 3.1, but when creating a new database, it is kdbx 4.
No auto upgrade available?

**Comment by J-Jamet** [comment]
Minimum requirements of database configuration must be met to automatically migrate to version 4.0 or 4.1.
The conditions are the same as those explained on the official website:
https://keepass.info/help/kb/kdbx_4.html
https://keepass.info/help/kb/kdbx_4.1.html
